# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# TODO: improve workflow https://medium.com/@cjolowicz/hypermodern-python-6-ci-cd-b233accfa2f6

name: Publish Package

on:
  workflow_dispatch:
  release:
    types:
      - publish

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Get Poetry version
      run: poetry --version
    - name: Check pyproject.toml validity
      run: poetry check --no-interaction
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.venv
        key: ${{ matrix.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ matrix.os }}-
    - name: Install dependencies
      if: steps.cache-dependencies.cache-hit != 'true'
      run: |
        poetry install --no-interaction
    - name: Build and publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --build
    
